# Generated by Django 3.2.7 on 2021-10-24 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Pedido',
            fields=[
                ('estadoPedido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('formaPago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Cabecera',
            fields=[
                ('pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estadoPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.estado_pedido')),
                ('formaPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.forma_pago')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rodado',
            name='descripcion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(36), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Pedidos_linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('precioPedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.pedidos_cabecera')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.producto')),
            ],
        ),
    ]
