# Generated by Django 3.2.7 on 2021-10-24 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda', '0002_auto_20211024_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_cabecera',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidos_cabecera',
            name='fechahora',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidos_linea',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.pedidos_cabecera'),
        ),
        migrations.AlterField(
            model_name='pedidos_linea',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.producto'),
        ),
    ]
