# Generated by Django 3.2.7 on 2021-11-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_productol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoL',
        ),
    ]
