# Generated by Django 3.2.7 on 2021-10-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_auto_20211024_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='fotos', verbose_name='Foto'),
        ),
    ]
