# Generated by Django 3.2.7 on 2021-11-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_delete_productol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
