# Generated by Django 3.2.9 on 2021-11-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sub_titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sub_titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=255)),
                ('secciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.secciones')),
            ],
        ),
    ]
