# Generated by Django 3.2.9 on 2021-11-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_secciones_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='LandingPage.pagina'),
        ),
    ]
