# Generated by Django 3.2.7 on 2021-11-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_alter_secciones_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='imagen',
            field=models.ImageField(upload_to='fotos', verbose_name='Foto'),
        ),
    ]
