# Generated by Django 3.2.7 on 2021-11-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_comprador',
            new_name='es_comprador',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_vendedor',
            new_name='es_vendedor',
        ),
    ]
